# Generated by Django 3.0 on 2020-12-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201221_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
