# Generated by Django 3.0 on 2020-12-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201221_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_broker', to='app1.Broker'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_customer', to='app1.Customer'),
        ),
    ]
