# Generated by Django 3.0 on 2020-12-22 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201222_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='time',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='connection',
            name='modified_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
