# Generated by Django 3.0 on 2020-12-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('rating', models.CharField(choices=[(1, 'worst'), (2, 'bad'), (3, 'average'), (4, 'good'), (5, 'excellent')], default=4, max_length=10)),
                ('created_time', models.DateTimeField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_broker', to='app1.Broker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_customer', to='app1.Customer')),
            ],
        ),
    ]
