# Generated by Django 3.0 on 2020-12-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20201229_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
