# Generated by Django 3.0 on 2020-12-31 10:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_connection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13),
        ),
    ]
