# Generated by Django 3.0 on 2020-12-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20201231_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='average_rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
