# Generated by Django 3.0 on 2021-01-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_broker_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField()),
                ('flag', models.BooleanField()),
                ('is_read', models.BooleanField(default=False)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_message', to='app1.Broker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_message', to='app1.Customer')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
