# Generated by Django 3.0 on 2021-01-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
